name: first-workflow
on: workflow_dispatch
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Hello World
        run: echo "Hello World!"
      - name: Printing Regards
        run: |
         echo "Thanks & Regards"  // changed the allignment
         echo "Pranai"
