name: excercise workflow
on: issues
jobs:
    firstJob:
        runs-on: ubuntu-latest
        steps:
            - name: Output Issue Title
              run: echo "Issue title is ${{ toJson(github.event.issue.title) }}"
