name: Azure Function App CI/CD for PROD

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter the branch to deploy'
        required: true
        default: 'main'

      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - Prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
       ref: ${{ github.event.inputs.branch }}

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Archive the function app code
    - name: Archive the code
      run: zip -r functionapp.zip .

    # Step 5: Deploy to Azure Function App
    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: 'frcupsi05xazf01'
        package: './functionapp.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD }}
